"""MkDocs build hooks. Registered via `hooks:` in mkdocs.yml."""


def on_page_markdown(markdown, page, config, files):
    """Point the "edit this page" button at the page's Notion source.

    edit_uri is deliberately left empty in mkdocs.yml (there's no meaningful
    "edit on GitHub" action for content generated by notion_sync.py), so
    page.edit_url is normally unset. For pages synced from Notion, front
    matter carries the original notion_url — use it here instead.
    """
    notion_url = page.meta.get("notion_url")
    if notion_url:
        page.edit_url = notion_url
    return markdown
