#!/usr/bin/env python3
"""
Sync Notion pages into MkDocs docs/notion/ folder as Markdown files.
Automatically updates the Notion section in mkdocs.yml.

Usage:
  NOTION_TOKEN=ntn_xxx NOTION_PAGE_ID=1fd9f2a93248826a83de816c57fc66b8 python3 notion_sync.py

Idempotent by design: re-running against an unchanged Notion tree produces
byte-identical output. Page identity is tracked by Notion page ID (not by
title/slug) in .notion-sync/manifest.json, which is what makes rename and
delete detection possible across runs — see README.md for the full pipeline
description.
"""

import json
import logging
import os
import re
import sys
from pathlib import Path, PurePosixPath
from urllib.parse import urlparse

logging.getLogger("notion_client").setLevel(logging.ERROR)

try:
    from notion_client import Client
except ImportError:
    print("ERROR: notion-client not installed. Run: pip install notion-client")
    sys.exit(1)

try:
    import requests
except ImportError:
    print("ERROR: requests not installed. Run: pip install requests")
    sys.exit(1)

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed. Run: pip install pyyaml")
    sys.exit(1)

NOTION_TOKEN = os.environ.get("NOTION_TOKEN", "")
NOTION_PAGE_ID = os.environ.get("NOTION_PAGE_ID", "")

ROOT = Path(__file__).parent
DOCS_DIR = ROOT / "docs"
NOTION_DIR = DOCS_DIR / "notion"
IMAGES_DIR = DOCS_DIR / "assets" / "notion-images"
MKDOCS_YML = ROOT / "mkdocs.yml"
MANIFEST_PATH = ROOT / ".notion-sync" / "manifest.json"
RECENTLY_UPDATED_PATH = DOCS_DIR / "recently-updated.md"

NAV_BEGIN = "# BEGIN NOTION NAV — auto-generated by notion_sync.py, do not edit by hand"
NAV_END = "# END NOTION NAV"
REDIRECTS_BEGIN = "# BEGIN NOTION REDIRECTS — auto-generated by notion_sync.py, do not edit by hand"
REDIRECTS_END = "# END NOTION REDIRECTS"

RELATED_MAX = 5
RECENTLY_UPDATED_MAX = 20

# Placeholder swapped for the correct "../.." prefix once a page's final
# output directory is known — lets block_to_md stay ignorant of where the
# page it's building will eventually live.
DOCS_ROOT_MARKER = "__DOCS_ROOT__/"


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text or "untitled"


def rich_text_to_md(rich_texts: list) -> str:
    result = ""
    for rt in rich_texts:
        text = rt.get("plain_text", "")
        ann = rt.get("annotations", {})
        href = rt.get("href")
        if ann.get("code"):
            text = f"`{text}`"
        if ann.get("bold"):
            text = f"**{text}**"
        if ann.get("italic"):
            text = f"*{text}*"
        if ann.get("strikethrough"):
            text = f"~~{text}~~"
        if href:
            text = f"[{text}]({href})"
        result += text
    return result


def get_all_blocks(client: Client, block_id: str) -> list:
    blocks = []
    cursor = None
    while True:
        kwargs = {"block_id": block_id, "page_size": 100}
        if cursor:
            kwargs["start_cursor"] = cursor
        resp = client.blocks.children.list(**kwargs)
        blocks.extend(resp.get("results", []))
        if not resp.get("has_more"):
            break
        cursor = resp.get("next_cursor")
    return blocks


# Maps Notion callout emojis → MkDocs admonition types
_CALLOUT_MAP = {
    "💡": "tip",    "🔥": "warning",  "⚠️": "warning",  "🚨": "danger",
    "❌": "failure", "✅": "success",  "ℹ️": "info",     "📝": "note",
    "🧠": "abstract","📌": "tip",     "🎯": "example",   "💬": "quote",
    "🤔": "question","👉": "tip",     "📢": "info",      "🔑": "tip",
    "⛔": "danger",  "🛑": "danger",  "📣": "info",      "🏆": "success",
}


class ImageDownloader:
    """Downloads Notion-hosted images once per block, under a stable
    filename keyed by the block id.

    Notion's file-hosted images are presigned S3 URLs that expire in about
    an hour — embedding them directly (the old behaviour) meant every
    screenshot silently 404'd shortly after publish. Downloading into
    docs/assets/notion-images/ fixes that, and keying by block id (rather
    than content hash) keeps re-syncs from re-downloading or renaming files
    that haven't actually changed.
    """

    def __init__(self, images_dir: Path):
        self.images_dir = images_dir
        self.used: set[str] = set()

    def download(self, url: str, block_id: str) -> str | None:
        if not url:
            return None
        ext = self._guess_ext(url)
        filename = f"{block_id.replace('-', '')}{ext}"
        dest = self.images_dir / filename
        self.used.add(filename)
        if not dest.exists():
            self.images_dir.mkdir(parents=True, exist_ok=True)
            try:
                resp = requests.get(url, timeout=30)
                resp.raise_for_status()
                dest.write_bytes(resp.content)
            except Exception as exc:  # noqa: BLE001 - best-effort, log and move on
                print(f"  ! image download failed for block {block_id}: {exc}")
                self.used.discard(filename)
                return None
        return f"{DOCS_ROOT_MARKER}assets/notion-images/{filename}"

    @staticmethod
    def _guess_ext(url: str) -> str:
        path = urlparse(url).path
        ext = Path(path).suffix
        if ext and len(ext) <= 5:
            return ext
        return ".png"

    def prune_unused(self) -> None:
        if not self.images_dir.exists():
            return
        for img in self.images_dir.iterdir():
            if img.is_file() and img.name not in self.used:
                img.unlink()
                print(f"  - removed unused image: assets/notion-images/{img.name}")


def block_to_md(block: dict, client: Client, images: ImageDownloader, depth: int = 0) -> str:
    btype = block.get("type", "")
    data = block.get(btype, {})
    indent = "  " * depth
    lines = []

    if btype == "paragraph":
        text = rich_text_to_md(data.get("rich_text", []))
        lines.append(f"{indent}{text}\n")

    elif btype in ("heading_1", "heading_2", "heading_3"):
        level = {"heading_1": "#", "heading_2": "##", "heading_3": "###"}[btype]
        text = rich_text_to_md(data.get("rich_text", []))
        lines.append(f"\n{level} {text}\n")

    elif btype == "bulleted_list_item":
        text = rich_text_to_md(data.get("rich_text", []))
        lines.append(f"{indent}- {text}\n")
        if block.get("has_children"):
            for child in get_all_blocks(client, block["id"]):
                lines.append(block_to_md(child, client, images, depth + 1))

    elif btype == "numbered_list_item":
        text = rich_text_to_md(data.get("rich_text", []))
        lines.append(f"{indent}1. {text}\n")
        if block.get("has_children"):
            for child in get_all_blocks(client, block["id"]):
                lines.append(block_to_md(child, client, images, depth + 1))

    elif btype == "code":
        lang = data.get("language", "plain text")
        if lang == "plain text":
            lang = "text"
        text = rich_text_to_md(data.get("rich_text", []))
        caption = rich_text_to_md(data.get("caption", []))
        caption_line = f"\n_{caption}_\n" if caption else ""
        lines.append(f"```{lang}\n{text}\n```{caption_line}\n")

    elif btype == "quote":
        text = rich_text_to_md(data.get("rich_text", []))
        lines.append(f"> {text}\n")

    elif btype == "callout":
        text = rich_text_to_md(data.get("rich_text", []))
        icon = data.get("icon", {}).get("emoji", "")
        admonition = _CALLOUT_MAP.get(icon, "note")
        title = icon if icon else ""
        header = f'!!! {admonition} "{title}"' if title else f"!!! {admonition}"
        lines.append(f"{header}\n    {text}\n")
        if block.get("has_children"):
            for child in get_all_blocks(client, block["id"]):
                child_md = block_to_md(child, client, images, 0)
                for ln in child_md.splitlines():
                    lines.append(f"    {ln}\n")

    elif btype == "toggle":
        text = rich_text_to_md(data.get("rich_text", []))
        lines.append(f'??? note "{text}"\n')
        if block.get("has_children"):
            for child in get_all_blocks(client, block["id"]):
                child_md = block_to_md(child, client, images, 0)
                for ln in child_md.splitlines():
                    lines.append(f"    {ln}\n")
        lines.append("\n")

    elif btype == "divider":
        lines.append("\n---\n")

    elif btype == "image":
        url = (data.get("external") or data.get("file") or {}).get("url", "")
        caption = rich_text_to_md(data.get("caption", []))
        local_path = images.download(url, block["id"])
        src = local_path or url
        lines.append(f"![{caption or 'image'}]({src})\n")
        if caption:
            lines.append(f"*{caption}*\n")

    elif btype == "to_do":
        text = rich_text_to_md(data.get("rich_text", []))
        checked = "x" if data.get("checked") else " "
        lines.append(f"{indent}- [{checked}] {text}\n")

    elif btype == "table":
        # Fetch rows and render as markdown table
        rows = get_all_blocks(client, block["id"])
        for i, row in enumerate(rows):
            cells = row.get("table_row", {}).get("cells", [])
            row_md = " | ".join(rich_text_to_md(cell) for cell in cells)
            lines.append(f"| {row_md} |\n")
            if i == 0:
                separator = " | ".join("---" for _ in cells)
                lines.append(f"| {separator} |\n")
        lines.append("\n")

    elif btype == "table_row":
        pass  # handled inside "table" above

    elif btype == "equation":
        expr = data.get("expression", "")
        lines.append(f"$${expr}$$\n")

    elif btype == "bookmark":
        url = data.get("url", "")
        caption = rich_text_to_md(data.get("caption", [])) or url
        lines.append(f"🔗 [{caption}]({url})\n")

    elif btype == "link_preview":
        url = data.get("url", "")
        lines.append(f"🔗 [{url}]({url})\n")

    # Generic children fallback (not for types already handling children above)
    if block.get("has_children") and btype not in (
        "table", "child_page", "child_database",
        "bulleted_list_item", "numbered_list_item", "callout", "toggle",
    ):
        for child in get_all_blocks(client, block["id"]):
            lines.append(block_to_md(child, client, images, depth + 1))

    return "".join(lines)


def get_page_title(page: dict) -> str:
    props = page.get("properties", {})
    for key in ("Name", "Title", "title", "name"):
        if key in props:
            prop = props[key]
            if prop.get("type") == "title":
                title = rich_text_to_md(prop.get("title", []))
                if title:
                    return title
    if page.get("object") == "block" and page.get("type") == "child_page":
        return page.get("child_page", {}).get("title", "untitled")
    return "untitled"


def extract_tags(body_lines: list) -> tuple:
    """Scan rendered lines for a "tags: X, Y" or "tag: X" pattern and strip it."""
    tags = []
    filtered = []
    for ln in body_lines:
        m = re.match(r"^tags?:\s*(.+)", ln.strip(), re.IGNORECASE)
        if m:
            tags = [t.strip() for t in m.group(1).split(",") if t.strip()]
        else:
            filtered.append(ln)
    return tags, filtered


_DESC_LINK_RE = re.compile(r"\[([^\]]*)\]\([^)]*\)")
_DESC_STRIP_RE = re.compile(r"[`*_>#\[\]!]")


def derive_description(body: str, max_len: int = 155) -> str:
    """First substantive plain-text line of the body, for the meta
    description tag and social-card subtitle — Material already reads
    page.meta.description, it just had nothing to read before this."""
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith(("!!!", "???", "```", "|", "-", "1.", ">", "$$")):
            continue
        text = _DESC_LINK_RE.sub(r"\1", line)
        text = _DESC_STRIP_RE.sub("", text).strip()
        if len(text) < 20:
            continue
        if len(text) > max_len:
            text = text[: max_len - 1].rsplit(" ", 1)[0] + "…"
        return text
    return ""


def walk_page(
    client: Client,
    page_id: str,
    output_dir: Path,
    images: ImageDownloader,
    records: list,
    indent: str = "",
    is_root: bool = False,
    parent_id: str = None,
) -> None:
    page = client.pages.retrieve(page_id=page_id)
    if page.get("object") != "page":
        return

    title = get_page_title(page)
    blocks = get_all_blocks(client, page_id)

    if not is_root:
        body_lines = [block_to_md(b, client, images) for b in blocks]
        tags, filtered = extract_tags(body_lines)

        filename = slugify(title) + ".md"
        filepath = output_dir / filename
        rel_path = filepath.relative_to(DOCS_DIR).as_posix()

        # Swap the docs-root marker for the real "../.."-style prefix now
        # that we know where this page will actually live.
        page_dir = filepath.parent
        prefix = os.path.relpath(DOCS_DIR, start=page_dir)
        prefix = "" if prefix == "." else prefix + "/"
        body = "".join(filtered).replace(DOCS_ROOT_MARKER, prefix)

        records.append({
            "id": page_id,
            "parent_id": parent_id,
            "title": title,
            "rel_path": rel_path,
            "body": body,
            "tags": tags,
            "description": derive_description(body),
            "last_edited_time": page.get("last_edited_time", ""),
            "created_time": page.get("created_time", ""),
            "notion_url": page.get("url", ""),
        })
        print(f"{indent}+ {title}  →  docs/{rel_path}")
    else:
        print(f"[root] {title}  →  skipped (container page)")

    child_pages = [b for b in blocks if b.get("type") == "child_page"]
    if child_pages:
        child_dir = output_dir / slugify(title) if not is_root else output_dir
        for child in child_pages:
            walk_page(client, child["id"], child_dir, images, records, indent + "  ", parent_id=page_id)


def compute_related(rec: dict, tag_index: dict) -> list:
    if not rec["tags"]:
        return []
    scores = {}
    others = {}
    for t in rec["tags"]:
        for other in tag_index.get(t.lower(), []):
            if other["id"] == rec["id"]:
                continue
            scores[other["id"]] = scores.get(other["id"], 0) + 1
            others[other["id"]] = other
    ranked = sorted(scores.items(), key=lambda kv: (-kv[1], others[kv[0]]["title"]))
    return [others[pid] for pid, _ in ranked[:RELATED_MAX]]


def relative_link(from_rel_path: str, to_rel_path: str) -> str:
    from_dir = str(PurePosixPath(from_rel_path).parent)
    return os.path.relpath(to_rel_path, start=from_dir)


def write_page(rec: dict, related: list) -> None:
    fm = ["---"]
    if rec["tags"]:
        fm.append("tags:")
        fm.extend(f"  - {t}" for t in rec["tags"])
    if rec.get("description"):
        fm.append(f"description: {json.dumps(rec['description'])}")
    if rec["notion_url"]:
        fm.append(f"notion_url: {json.dumps(rec['notion_url'])}")
    if rec["created_time"]:
        fm.append(f"created_time: {json.dumps(rec['created_time'])}")
    if rec["last_edited_time"]:
        fm.append(f"last_edited_time: {json.dumps(rec['last_edited_time'])}")
    fm.append("---\n\n")
    front_matter = "\n".join(fm)

    parts = [front_matter, f"# {rec['title']}\n\n", rec["body"]]

    if related:
        parts.append("\n## Related\n\n")
        for r in related:
            link = relative_link(rec["rel_path"], r["rel_path"])
            parts.append(f"- [{r['title']}]({link})\n")

    parts.append('\n--8<-- "abbreviations.md"\n')

    filepath = DOCS_DIR / rec["rel_path"]
    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("".join(parts), encoding="utf-8")


def compute_has_children(records: list) -> set:
    """rel_paths of pages that are themselves containers (have sub-pages).

    A container page's own file and its children's directory share a slug
    (see walk_page), which is also exactly when a page can end up sharing
    its title with one of its own children (e.g. a "Kafka" page containing
    a single "Kafka" sub-page) -- checking body content to tell them apart
    is fragile (a container can pick up real content of its own later), so
    anything that consumes records for a flat/deduplicated view should key
    off this structural fact instead.
    """
    by_parent = {}
    for rec in records:
        parent = str(PurePosixPath(rec["rel_path"]).parent)
        by_parent.setdefault(parent, []).append(rec["rel_path"])

    has_children = set()
    for rec in records:
        page_dir = str(PurePosixPath(rec["rel_path"]).with_suffix(""))
        if page_dir in by_parent:
            has_children.add(rec["rel_path"])
    return has_children


def build_nav_tree(records: list) -> list:
    """Build nav tree mirroring Notion hierarchy.

    - Root page and its direct children are flat at the top level.
    - Pages that have sub-pages become collapsible sections.
    """
    by_parent = {}
    for rec in records:
        parent = str(PurePosixPath(rec["rel_path"]).parent)
        by_parent.setdefault(parent, []).append((rec["title"], rec["rel_path"]))

    has_children = compute_has_children(records)

    def make_items(parent_dir: str) -> list:
        items = []
        for title, rel_path in by_parent.get(parent_dir, []):
            page_dir = str(PurePosixPath(rel_path).with_suffix(""))
            if rel_path in has_children:
                # The page itself becomes a section (its Notion sub-pages
                # nest under it), so it needs its own nav entry too -- but
                # labelling that "Overview" instead of repeating the
                # section's own title avoids the section appearing to
                # contain a duplicate of itself in the sidebar. (Material's
                # navigation.indexes would normally collapse this, but that
                # feature depends on use_directory_urls, which is off here
                # for the offline plugin's file:// support.)
                sub = [{"Overview": rel_path}] + make_items(page_dir)
                items.append({title: sub})
            else:
                items.append({title: rel_path})
        return items

    return make_items("notion")


def render_yaml_block(payload: list, indent: int = 2) -> list:
    """YAML-safe rendering via PyYAML — replaces manual string-building so
    titles containing `: { } [ ] # & " '` etc. can never corrupt mkdocs.yml.
    """
    dumped = yaml.safe_dump(
        payload, allow_unicode=True, sort_keys=False, default_flow_style=False, width=1000,
    )
    pad = " " * indent
    return [(pad + line if line.strip() else line) for line in dumped.rstrip("\n").split("\n")]


def update_yaml_section(path: Path, begin: str, end: str, new_lines: list) -> None:
    text = path.read_text()
    lines = text.split("\n")
    start_idx = end_idx = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if start_idx is None and stripped == begin:
            start_idx = i
        elif start_idx is not None and stripped == end:
            end_idx = i
            break
    if start_idx is None or end_idx is None:
        raise RuntimeError(
            f"Could not find markers in {path.name}: "
            f"begin={begin!r} ({'found' if start_idx is not None else 'MISSING'}), "
            f"end={end!r} ({'found' if end_idx is not None else 'MISSING'})"
        )
    result = lines[: start_idx + 1] + new_lines + lines[end_idx:]
    path.write_text("\n".join(result))


def generate_recently_updated(records: list) -> None:
    ranked = sorted(records, key=lambda r: r["last_edited_time"], reverse=True)[:RECENTLY_UPDATED_MAX]
    lines = [
        "---\nhide:\n  - toc\n---\n\n",
        "# Recently Updated\n\n",
        "Ranked by last edit in Notion. Regenerated on every sync.\n\n",
    ]
    for i, r in enumerate(ranked, 1):
        when = r["last_edited_time"].split("T")[0] if r["last_edited_time"] else "unknown"
        lines.append(f"{i}. [{r['title']}]({r['rel_path']}) — {when}\n")
    lines.append('\n--8<-- "abbreviations.md"\n')
    RECENTLY_UPDATED_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"docs/recently-updated.md  →  regenerated ({len(ranked)} entries)")


def generate_home_page(records: list) -> None:
    """Auto-generate index.md with quick-link cards for every synced page."""
    icons = {
        "kafka": "🟠", "kubernetes": "☸️", "k8s": "☸️", "kk8s": "☸️",
        "test": "🧪", "notes": "📒", "archive": "🗄️",
    }

    def pick_icon(title: str) -> str:
        low = title.lower()
        for key, icon in icons.items():
            if key in low:
                return icon
        return "📄"

    has_children = compute_has_children(records)

    cards = []
    for rec in records:
        # A container page (has its own sub-pages) can share its exact
        # title with one of its children -- e.g. a "Kafka" page containing
        # a "Kafka" sub-page -- which would otherwise produce two visibly
        # identical cards here. Whether the container also happens to have
        # some body text of its own isn't a reliable signal (it might
        # today and not tomorrow); its rel_path showing up in has_children
        # is the structural fact that actually distinguishes it.
        if rec["rel_path"] in has_children:
            continue
        icon = pick_icon(rec["title"])
        blurb = rec["description"] or f"Quick access to {rec['title']} notes."
        cards.append(
            f"-   {icon} **[{rec['title']}]({rec['rel_path']})**\n\n"
            f"    {blurb}"
        )

    cards_block = "\n\n".join(cards)

    content = f"""# MuzOps Learning Zone

> Personal learning notes on Kubernetes, DevOps, Kafka, and Cloud Engineering.

New here? Start with [Start Here](start-here.md) for a suggested reading order.

---

## Quick Links

<div class="grid cards" markdown>

{cards_block}

</div>

---

## Recently Read

<div id="recent-pages">
  <em>Loading recently visited pages...</em>
</div>
"""

    (DOCS_DIR / "index.md").write_text(content, encoding="utf-8")
    print(f"index.md    →  home page regenerated ({len(records)} quick links)")


def load_manifest() -> dict:
    if MANIFEST_PATH.exists():
        try:
            data = json.loads(MANIFEST_PATH.read_text())
            data.setdefault("pages", {})
            data.setdefault("redirects", {})
            return data
        except json.JSONDecodeError:
            print("  ! .notion-sync/manifest.json is corrupt, starting fresh")
    return {"pages": {}, "redirects": {}}


def save_manifest(manifest: dict) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def apply_renames_and_deletions(records: list, old_pages: dict, redirects: dict) -> None:
    by_id = {r["id"]: r for r in records}
    current_ids = set(by_id)

    for pid, rec in by_id.items():
        old = old_pages.get(pid)
        if old and old["rel_path"] != rec["rel_path"]:
            old_file = DOCS_DIR / old["rel_path"]
            if old_file.exists():
                old_file.unlink()
                print(f"  ~ renamed: docs/{old['rel_path']}  →  docs/{rec['rel_path']}")
            # Collapse any earlier redirect chain that pointed at the old path.
            for k, v in list(redirects.items()):
                if v == old["rel_path"]:
                    redirects[k] = rec["rel_path"]
            redirects[old["rel_path"]] = rec["rel_path"]

    for pid, old in old_pages.items():
        if pid in current_ids:
            continue
        old_file = DOCS_DIR / old["rel_path"]
        if old_file.exists():
            old_file.unlink()
            print(f"  - removed: docs/{old['rel_path']}")
            for parent in old_file.parents:
                if parent == DOCS_DIR:
                    break
                if parent.is_dir() and not any(parent.iterdir()):
                    parent.rmdir()


def main():
    if not NOTION_TOKEN:
        print("ERROR: Set NOTION_TOKEN environment variable.")
        sys.exit(1)
    if not NOTION_PAGE_ID:
        print("ERROR: Set NOTION_PAGE_ID environment variable.")
        sys.exit(1)

    client = Client(auth=NOTION_TOKEN)
    images = ImageDownloader(IMAGES_DIR)
    manifest = load_manifest()
    old_pages = manifest["pages"]
    redirects = dict(manifest["redirects"])

    records = []
    walk_page(client, NOTION_PAGE_ID, NOTION_DIR, images, records, is_root=True)

    apply_renames_and_deletions(records, old_pages, redirects)
    images.prune_unused()

    tag_index = {}
    for rec in records:
        for t in rec["tags"]:
            tag_index.setdefault(t.lower(), []).append(rec)

    for rec in records:
        write_page(rec, compute_related(rec, tag_index))

    new_pages = {
        rec["id"]: {"rel_path": rec["rel_path"], "title": rec["title"], "last_edited_time": rec["last_edited_time"]}
        for rec in records
    }
    save_manifest({"pages": new_pages, "redirects": redirects})

    nav_tree = build_nav_tree(records)
    update_yaml_section(MKDOCS_YML, NAV_BEGIN, NAV_END, render_yaml_block([{"Notion": nav_tree}]))
    print(f"mkdocs.yml  →  Notion nav section updated ({len(records)} pages)")

    redirect_maps = dict(sorted(redirects.items())) if redirects else {}
    update_yaml_section(
        MKDOCS_YML, REDIRECTS_BEGIN, REDIRECTS_END,
        render_yaml_block([{"redirects": {"redirect_maps": redirect_maps}}]),
    )
    print(f"mkdocs.yml  →  redirects updated ({len(redirect_maps)} entries)")

    generate_recently_updated(records)
    generate_home_page(records)

    print(f"\nDone. {len(records)} page(s) synced.")


if __name__ == "__main__":
    main()
