"""
Tests for the sync engine's correctness properties, run against a fake
Notion client (no live API access needed):

- idempotency: same Notion state in -> byte-identical output on re-run
- rename detection: title change updates the file/nav in place + records a redirect
- delete detection: removed Notion page removes its file
- YAML-safe nav/redirects generation for titles with `: & "` etc.
- image download + relative-path rewriting

Run with: python3 -m pytest tests/ -v   (or: python3 tests/test_notion_sync.py)
"""

import importlib
import shutil
import sys
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


def rt(text):
    return [{"plain_text": text, "annotations": {}, "href": None}]


def title_page(title):
    return {"Name": {"type": "title", "title": rt(title)}}


class FakeNotionClient:
    """Minimal stand-in for notion_client.Client covering exactly what
    notion_sync.py calls: pages.retrieve and blocks.children.list."""

    def __init__(self, pages: dict, children: dict):
        self._pages = pages
        self._children = children
        self.pages = mock.Mock(retrieve=self._retrieve)
        self.blocks = mock.Mock()
        self.blocks.children = mock.Mock(list=self._list_children)

    def _retrieve(self, page_id):
        return self._pages[page_id]

    def _list_children(self, block_id, page_size=100, start_cursor=None):
        return {"results": self._children.get(block_id, []), "has_more": False, "next_cursor": None}


def make_page(page_id, title, last_edited="2026-08-30T00:00:00.000Z", created="2026-08-01T00:00:00.000Z"):
    return {
        "object": "page",
        "id": page_id,
        "properties": title_page(title),
        "last_edited_time": last_edited,
        "created_time": created,
        "url": f"https://www.notion.so/{page_id}",
    }


def para(text):
    return {"type": "paragraph", "paragraph": {"rich_text": rt(text)}, "has_children": False}


def child_page_block(page_id, title):
    return {"type": "child_page", "id": page_id, "child_page": {"title": title}, "has_children": False}


def image_block(block_id, url):
    return {
        "type": "image",
        "id": block_id,
        "image": {"external": {"url": url}, "caption": []},
        "has_children": False,
    }


MKDOCS_YML_FIXTURE = """\
nav:
  - Home: index.md
  # BEGIN NOTION NAV — auto-generated by notion_sync.py, do not edit by hand
  - Notion: []
  # END NOTION NAV

plugins:
  - redirects:
      redirect_maps:
  # BEGIN NOTION REDIRECTS — auto-generated by notion_sync.py, do not edit by hand
        placeholder: placeholder
  # END NOTION REDIRECTS
"""


class SyncTestCase(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(mock.MagicMock().__class__.__name__)  # placeholder, replaced below
        import tempfile
        self.tmpdir = Path(tempfile.mkdtemp(prefix="notion-sync-test-"))
        self.addCleanup(shutil.rmtree, self.tmpdir, ignore_errors=True)

        (self.tmpdir / "docs").mkdir()
        (self.tmpdir / "mkdocs.yml").write_text(MKDOCS_YML_FIXTURE)

        import notion_sync
        importlib.reload(notion_sync)
        self.mod = notion_sync

        self.mod.ROOT = self.tmpdir
        self.mod.DOCS_DIR = self.tmpdir / "docs"
        self.mod.NOTION_DIR = self.mod.DOCS_DIR / "notion"
        self.mod.IMAGES_DIR = self.mod.DOCS_DIR / "assets" / "notion-images"
        self.mod.MKDOCS_YML = self.tmpdir / "mkdocs.yml"
        self.mod.MANIFEST_PATH = self.tmpdir / ".notion-sync" / "manifest.json"
        self.mod.RECENTLY_UPDATED_PATH = self.mod.DOCS_DIR / "recently-updated.md"
        self.mod.NOTION_TOKEN = "test-token"
        self.mod.NOTION_PAGE_ID = "root"

    def run_sync(self, pages, children, image_bytes=b"fake-png-bytes"):
        fake_client = FakeNotionClient(pages, children)
        with mock.patch.object(self.mod, "Client", return_value=fake_client), \
             mock.patch.object(self.mod.requests, "get") as mock_get:
            mock_get.return_value = mock.Mock(content=image_bytes, raise_for_status=lambda: None)
            self.mod.main()

    def read(self, rel):
        return (self.mod.DOCS_DIR / rel).read_text()

    def exists(self, rel):
        return (self.mod.DOCS_DIR / rel).exists()

    # -- fixture tree ------------------------------------------------------
    def base_tree(self):
        pages = {
            "root": make_page("root", "Notes"),
            "page-a": make_page("page-a", "Kubernetes"),
            "page-a-child": make_page("page-a-child", "Operators"),
            "page-b": make_page("page-b", "Kafka"),
        }
        children = {
            "root": [child_page_block("page-a", "Kubernetes"), child_page_block("page-b", "Kafka")],
            "page-a": [para("tags: Kubernetes, Ops"), para("K8s content"), child_page_block("page-a-child", "Operators")],
            "page-a-child": [para("tags: Kubernetes, Operators"), para("Operator content")],
            "page-b": [para("tags: Kafka"), image_block("img-1", "https://notion-s3.example/expiring.png?sig=xyz"), para("Kafka content")],
        }
        return pages, children

    def test_first_sync_writes_expected_files_and_metadata(self):
        pages, children = self.base_tree()
        self.run_sync(pages, children)

        self.assertTrue(self.exists("notion/kubernetes.md"))
        self.assertTrue(self.exists("notion/kubernetes/operators.md"))
        self.assertTrue(self.exists("notion/kafka.md"))

        kafka = self.read("notion/kafka.md")
        self.assertIn("tags:\n  - Kafka", kafka)
        self.assertIn("notion_url:", kafka)
        self.assertIn("last_edited_time:", kafka)
        # image downloaded locally, not linking Notion's expiring URL
        self.assertNotIn("notion-s3.example", kafka)
        self.assertIn("../assets/notion-images/img1.png", kafka)
        self.assertTrue((self.mod.IMAGES_DIR / "img1.png").exists())

        # shared "Kubernetes" tag -> related section on both sides
        kube = self.read("notion/kubernetes.md")
        operators = self.read("notion/kubernetes/operators.md")
        self.assertIn("## Related", kube)
        self.assertIn("operators.md", kube)
        self.assertIn("## Related", operators)
        self.assertIn("../kubernetes.md", operators)

        # nav regenerated
        yml = self.mod.MKDOCS_YML.read_text()
        self.assertIn("Kubernetes:", yml)
        self.assertIn("notion/kafka.md", yml)

        manifest = self.mod.load_manifest()
        self.assertEqual(set(manifest["pages"]), {"page-a", "page-a-child", "page-b"})

    def test_rerun_with_unchanged_tree_is_idempotent(self):
        pages, children = self.base_tree()
        self.run_sync(pages, children)
        first_kafka = self.read("notion/kafka.md")
        first_kube = self.read("notion/kubernetes.md")
        first_yml = self.mod.MKDOCS_YML.read_text()
        first_manifest = self.mod.MANIFEST_PATH.read_text()

        self.run_sync(pages, children)

        self.assertEqual(first_kafka, self.read("notion/kafka.md"))
        self.assertEqual(first_kube, self.read("notion/kubernetes.md"))
        self.assertEqual(first_yml, self.mod.MKDOCS_YML.read_text())
        self.assertEqual(first_manifest, self.mod.MANIFEST_PATH.read_text())

    def test_rename_updates_file_and_records_redirect_not_duplicate(self):
        pages, children = self.base_tree()
        self.run_sync(pages, children)
        self.assertTrue(self.exists("notion/kafka.md"))

        # Rename "Kafka" -> "Kafka & Streaming" (also exercises YAML escaping of "&")
        pages["page-b"] = make_page("page-b", "Kafka & Streaming", last_edited="2026-08-31T00:00:00.000Z")
        self.run_sync(pages, children)

        self.assertFalse(self.exists("notion/kafka.md"), "old slug must not linger after a rename")
        self.assertTrue(self.exists("notion/kafka-streaming.md"))

        manifest = self.mod.load_manifest()
        self.assertEqual(manifest["redirects"].get("notion/kafka.md"), "notion/kafka-streaming.md")

        yml = self.mod.MKDOCS_YML.read_text()
        self.assertIn("notion/kafka.md: notion/kafka-streaming.md", yml)
        # exactly one Kafka entry in nav, not a duplicate of old + new
        self.assertEqual(yml.count("notion/kafka-streaming.md"), 2)  # nav entry + redirect target
        self.assertNotIn("notion/kafka.md:", yml.replace("notion/kafka.md: notion/kafka-streaming.md", ""))

    def test_delete_removes_file_and_prunes_empty_dir(self):
        pages, children = self.base_tree()
        self.run_sync(pages, children)
        self.assertTrue(self.exists("notion/kubernetes/operators.md"))

        del pages["page-a-child"]
        children["page-a"] = [para("tags: Kubernetes, Ops"), para("K8s content")]
        self.run_sync(pages, children)

        self.assertFalse(self.exists("notion/kubernetes/operators.md"))
        self.assertFalse((self.mod.DOCS_DIR / "notion" / "kubernetes").exists(), "emptied directory should be pruned")

        manifest = self.mod.load_manifest()
        self.assertNotIn("page-a-child", manifest["pages"])

    def test_unused_images_are_pruned_after_removal(self):
        pages, children = self.base_tree()
        self.run_sync(pages, children)
        self.assertTrue((self.mod.IMAGES_DIR / "img1.png").exists())

        children["page-b"] = [para("tags: Kafka"), para("Kafka content, image removed")]
        self.run_sync(pages, children)

        self.assertFalse((self.mod.IMAGES_DIR / "img1.png").exists())


if __name__ == "__main__":
    unittest.main()
